# Generated by Django 4.2 on 2024-08-02 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('nationality', models.CharField(max_length=25, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Model')),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('contry', models.CharField(max_length=25, verbose_name='Contry')),
                ('status', models.BooleanField(verbose_name='Stauts')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='Natinal')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Productes',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('screnn_size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Screen size')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
            bases=('product.product',),
        ),
    ]
