# Generated by Django 4.2 on 2024-08-03 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(default='', max_length=20, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inventory'),
        ),
    ]
